# Generated by Django 3.2.5 on 2021-07-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tweet', '0004_alter_tweetcomment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetcomment',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
