# Generated by Django 3.2.5 on 2021-07-25 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tweet', '0006_tweetcomment_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetcomment',
            name='tweet',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Tweet.tweet'),
        ),
    ]
