# Generated by Django 3.2.5 on 2021-07-25 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tweet', '0007_alter_tweetcomment_tweet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetcomment',
            name='active',
        ),
        migrations.AlterField(
            model_name='tweetcomment',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Tweet.tweet'),
        ),
    ]
