# Generated by Django 3.2.5 on 2021-07-24 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_auto_20210724_0619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='target',
            new_name='follows',
        ),
    ]
